# Generated by Django 4.2 on 2026-06-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Sensor IP',
                'verbose_name_plural': 'Sensor IPs',
                'db_table': 'sensor_ip_db',
            },
        ),
        migrations.CreateModel(
            name='MobileCheckDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=100)),
                ('temperature', models.IntegerField()),
                ('co2', models.IntegerField()),
                ('rssi', models.IntegerField()),
                ('receiver', models.CharField(max_length=100)),
                ('sensing_time', models.FloatField()),
            ],
            options={
                'verbose_name': 'Sensor Check (Mobile)',
                'verbose_name_plural': 'Sensor Check (Mobile)',
                'db_table': 'sensor_mobile_check_db',
            },
        ),
        migrations.CreateModel(
            name='SensorCheckDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=100)),
                ('temperature', models.IntegerField()),
                ('co2', models.IntegerField()),
                ('sensing_time', models.FloatField()),
            ],
            options={
                'verbose_name': 'Sensor Check (Direct)',
                'verbose_name_plural': 'Sensor Check (Direct)',
                'db_table': 'sensor_sensor_check_db',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=100)),
                ('mac', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('direct', 'Direct'), ('mobile', 'Mobile')], max_length=20)),
                ('temperature', models.FloatField()),
                ('co2', models.IntegerField()),
                ('sensing_time', models.FloatField()),
                ('rssi', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sensor Data',
                'verbose_name_plural': 'Sensor Data',
                'db_table': 'sensor_sensor_data',
            },
        ),
        migrations.CreateModel(
            name='SensorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Sensor Location',
                'verbose_name_plural': 'Sensor Locations',
                'db_table': 'sensor_location',
            },
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['sensor', 'sensing_time'], name='sensor_sens_sensor_47ecdb_idx'),
        ),
    ]
