# Generated by Django 5.2.8 on 2026-06-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWSLatest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationID', models.CharField(max_length=100, unique=True)),
                ('obsTimeUtc', models.DateTimeField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('windSpeed', models.FloatField(blank=True, null=True)),
                ('windGust', models.FloatField(blank=True, null=True)),
                ('winddir', models.IntegerField(blank=True, null=True)),
                ('precipRate', models.FloatField(blank=True, null=True)),
                ('dewpoint', models.FloatField(blank=True, null=True)),
                ('heatIndex', models.FloatField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PWS Latest',
                'verbose_name_plural': 'PWS Latest',
                'db_table': 'pws_latest',
            },
        ),
        migrations.CreateModel(
            name='PWSStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationID', models.CharField(max_length=100, unique=True)),
                ('stationName', models.CharField(blank=True, max_length=200)),
                ('neighborhood', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('softwareType', models.CharField(blank=True, max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PWS Station',
                'verbose_name_plural': 'PWS Stations',
                'db_table': 'pws_station',
            },
        ),
        migrations.CreateModel(
            name='PWSObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationID', models.CharField(db_index=True, max_length=100)),
                ('obsTimeUtc', models.DateTimeField(db_index=True)),
                ('obsTimeLocal', models.CharField(max_length=100)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('dewpoint', models.FloatField(blank=True, null=True)),
                ('heatIndex', models.FloatField(blank=True, null=True)),
                ('windChill', models.FloatField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('windSpeed', models.FloatField(blank=True, null=True)),
                ('windGust', models.FloatField(blank=True, null=True)),
                ('winddir', models.IntegerField(blank=True, null=True)),
                ('precipRate', models.FloatField(blank=True, null=True)),
                ('precipTotal', models.FloatField(blank=True, null=True)),
                ('solarRadiation', models.FloatField(blank=True, null=True)),
                ('uv', models.FloatField(blank=True, null=True)),
                ('qcStatus', models.IntegerField(default=-1)),
            ],
            options={
                'verbose_name': 'PWS Observation',
                'verbose_name_plural': 'PWS Observations',
                'db_table': 'pws_observation',
                'indexes': [models.Index(fields=['stationID', 'obsTimeUtc'], name='pws_observa_station_5320ab_idx'), models.Index(fields=['stationID'], name='pws_observa_station_ba50b8_idx'), models.Index(fields=['obsTimeUtc'], name='pws_observa_obsTime_d4de2c_idx')],
            },
        ),
    ]
