# Generated by Django 5.2.8 on 2026-06-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_pwslatest_pwsstation_pwsobservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwsstation',
            name='country',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='pwsstation',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pwsstation',
            name='softwareType',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pwsstation',
            name='stationName',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
