# Generated by Django 5.2.8 on 2026-06-30 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_alter_pwsstation_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cctvID', models.CharField(max_length=100, unique=True)),
                ('pws_station', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CCTV Station',
                'verbose_name_plural': 'CCTV Stations',
                'db_table': 'cctv_station',
            },
        ),
        migrations.CreateModel(
            name='CCTVRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('precipRate_trigger', models.FloatField()),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('completed', 'Completed'), ('failed', 'Failed')], default='recording', max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('file_size_mb', models.FloatField(blank=True, null=True)),
                ('cctv_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.cctvstation')),
            ],
            options={
                'verbose_name': 'CCTV Recording',
                'verbose_name_plural': 'CCTV Recordings',
                'db_table': 'cctv_recording',
                'indexes': [models.Index(fields=['cctv_station', 'start_time'], name='cctv_record_cctv_st_eaafa6_idx'), models.Index(fields=['status'], name='cctv_record_status_a1a25b_idx')],
            },
        ),
    ]
